### ISSUE TITLE
Bug: Generating with custom sprites on Linux

### ISSUE THREAD

**Issue by BriGuy7727** [BriGuy7727/Archipelago#1]
### What happened?

Attempting to use custom sprites doesn't play nice on Linux; probably an issue with building the directory from which the sprites are supposed to be imported:

albrekka@albrekka-desktop:/mnt/GameCollectionDos/Randomizers/Archipelago$ ./ArchipelagoSNIClient AP_61320515891334224099_P9_Worldly_Bun.apff6wc
/mnt/GameCollectionDos/Randomizers/Archipelago/custom_worlds/yooka_laylee.apworld/yooka_laylee/__init__.py:45: SyntaxWarning: "is" with a literal. Did you mean "=="?
/mnt/GameCollectionDos/Randomizers/Archipelago/custom_worlds/yooka_laylee.apworld/yooka_laylee/__init__.py:45: SyntaxWarning: "is" with a literal. Did you mean "=="?
/mnt/GameCollectionDos/Randomizers/Archipelago/custom_worlds/yooka_laylee.apworld/yooka_laylee/__init__.py:45: SyntaxWarning: "is" with a literal. Did you mean "=="?
/mnt/GameCollectionDos/Randomizers/Archipelago/custom_worlds/yooka_laylee.apworld/yooka_laylee/__init__.py:45: SyntaxWarning: "is" with a literal. Did you mean "=="?
Archipelago (0.5.0) logging initialized on Linux-5.15.0-117-generic-x86_64-with-glibc2.35 running Python 3.11.9 (frozen)
Patch file was supplied. Creating sfc rom..
Version   1.4.2
Generated 2024-07-29 16:43:33
Input     Final Fantasy III (USA).sfc
AP Data   AP_61320515891334224099_P9_Worldly_Bun.applacements
Output    AP_61320515891334224099_P9_Worldly_Bun.sfc
Log       AP_61320515891334224099_P9_Worldly_Bun.txt
Seed      AP_61320515891334224099_P9_Worldly_Bun
Flags     -cg -oa 2.2.2.2.6.6.4.9.9 -ob 3.1.1.2.9.9.4.12.12.10.21.21 -oc 30.8.8.1.1.11.8 -od 59.1.1.11.31 -sc1 terra -sc2 shadow -sc3 relm -sal -eu -csrp 80 125 -fst -brl -slr 3 5 -lmprp 75 125 -lel -srr 25 35 -rnl -rnc -sdr 1 2 -das -dda -dns -sch -scis -com 98989898989898989898989898 -rec1 28 -rec2 27 -xpm 3 -mpm 5 -gpm 5 -nxppd -lsced 2 -hmced 2 -xgced 2 -ase 2 -msl 40 -sed -bbs -drloc shuffle -stloc mix -be -bnu -res -fer 0 -escr 100 -dgne -wnz -mmnu -cmd -esr 2 5 -elrt -ebr 82 -emprp 75 125 -nm1 random -rnl1 -rns1 -nm2 random -rnl2 -rns2 -nmmi -mmprp 75 125 -gp 5000 -smc 3 -sto 1 -ieor 33 -ieror 33 -ir stronger -csb 6 14 -mca -stra -saw -sisr 20 -sprp 75 125 -sdm 5 -npi -sebr -snsb -snee -snil -ccsr 20 -chrm 0 0 -cms -name JESSIE.WREN.MOG.SEIFER.SABIN.BLAZE.KABRIN.SARISA.MAUDE.GAU.PAPRUS.RIKU.YOSHI.SCHALA -cpor 295.310.10.276.330.377.251.304.257.367.88.395.286.75.297 -cspr 78.312.10.281.5.334.258.143.264.68.146.348.291.115.234.87.354.243.207.63 -cspp 1.1.5.4.0.2.1.2.3.2.5.1.0.2.1.6.6.1.0.3 -frw -wmhc -cor 100 -crr 100 -crvr 100 120 -crm -ari -anca -adeh -ame 1 -nmc -noshoes -u254 -nfps -fs -fe -fvd -fr -fj -fbs -fedc -fc -ond -etn
Hash      Boy, Bandit, Leo, Bird
Version   1.4.2
Generated 2024-07-29 16:43:33
Input     Final Fantasy III (USA).sfc
AP Data   AP_61320515891334224099_P9_Worldly_Bun.applacements
Output    AP_61320515891334224099_P9_Worldly_Bun.sfc
Log       AP_61320515891334224099_P9_Worldly_Bun.txt
Seed      AP_61320515891334224099_P9_Worldly_Bun
Flags     -cg -oa 2.2.2.2.6.6.4.9.9 -ob 3.1.1.2.9.9.4.12.12.10.21.21 -oc 30.8.8.1.1.11.8 -od 59.1.1.11.31 -sc1 terra -sc2 shadow -sc3 relm -sal -eu -csrp 80 125 -fst -brl -slr 3 5 -lmprp 75 125 -lel -srr 25 35 -rnl -rnc -sdr 1 2 -das -dda -dns -sch -scis -com 98989898989898989898989898 -rec1 28 -rec2 27 -xpm 3 -mpm 5 -gpm 5 -nxppd -lsced 2 -hmced 2 -xgced 2 -ase 2 -msl 40 -sed -bbs -drloc shuffle -stloc mix -be -bnu -res -fer 0 -escr 100 -dgne -wnz -mmnu -cmd -esr 2 5 -elrt -ebr 82 -emprp 75 125 -nm1 random -rnl1 -rns1 -nm2 random -rnl2 -rns2 -nmmi -mmprp 75 125 -gp 5000 -smc 3 -sto 1 -ieor 33 -ieror 33 -ir stronger -csb 6 14 -mca -stra -saw -sisr 20 -sprp 75 125 -sdm 5 -npi -sebr -snsb -snee -snil -ccsr 20 -chrm 0 0 -cms -name JESSIE.WREN.MOG.SEIFER.SABIN.BLAZE.KABRIN.SARISA.MAUDE.GAU.PAPRUS.RIKU.YOSHI.SCHALA -cpor 295.310.10.276.330.377.251.304.257.367.88.395.286.75.297 -cspr 78.312.10.281.5.334.258.143.264.68.146.348.291.115.234.87.354.243.207.63 -cspp 1.1.5.4.0.2.1.2.3.2.5.1.0.2.1.6.6.1.0.3 -frw -wmhc -cor 100 -crr 100 -crvr 100 120 -crm -ari -anca -adeh -ame 1 -nmc -noshoes -u254 -nfps -fs -fe -fvd -fr -fj -fbs -fedc -fc -ond -etn
Hash      Boy, Bandit, Leo, Bird
  File "/mnt/GameCollectionDos/Randomizers/Archipelago/lib/worlds/ff6wc/patch.py", line 108, in write_rom_from_gen_data
    wc.main(wc_args)
  File "/mnt/GameCollectionDos/Randomizers/Archipelago/lib/worlds/ff6wc/WorldsCollide/wc.py", line 14, in main
    data = Data(memory.rom, args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/GameCollectionDos/Randomizers/Archipelago/lib/worlds/ff6wc/WorldsCollide/data/data.py", line 30, in __init__
    self.characters.mod()
  File "/mnt/GameCollectionDos/Randomizers/Archipelago/lib/worlds/ff6wc/WorldsCollide/data/characters.py", line 145, in mod
    self.character_sprites.mod()
  File "/mnt/GameCollectionDos/Randomizers/Archipelago/lib/worlds/ff6wc/WorldsCollide/data/character_sprites.py", line 89, in mod
    self.mod_character_sprites()
  File "/mnt/GameCollectionDos/Randomizers/Archipelago/lib/worlds/ff6wc/WorldsCollide/data/character_sprites.py", line 66, in mod_character_sprites
    sprite_data = list(pkgutil.get_data(__name__, sprite_file))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pkgutil.py", line 640, in get_data
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data

[Errno 2] No such file or directory: '/mnt/GameCollectionDos/Randomizers/Archipelago/lib/worlds/ff6wc/WorldsCollide/data/mnt/GameCollectionDos/Randomizers/Archipelago/lib/worlds/ff6wc/WorldsCollide/graphics/sprites/custom/Jessie-HoxNorf-FF7.bin'

### What were the expected results?

Custom sprites shouldn't be an issue on Linux as they're fine on Windows (where I've tested)

### Software

Local generation

**Comment by beauxq** [comment]
fixed by
https://github.com/beauxq/Archipelago/pull/4/commits/3284cb7322555886af0479adbebabed05b79cedb
and
https://github.com/beauxq/Archipelago/pull/4/commits/da8712ba04c5bc0652e2b3ed7c90b1b50ed1b980
